/** DTO de dossiers — source unique = le contrat partagé (@capclair/contract). */
export {
  ConfirmAiConsentInputSchema,
  CaseFileStatusResponseSchema,
  CaseFileResultResponseSchema,
  CaseFileHistoryResponseSchema,
  StartAnalysisResponseSchema,
  AnalysisStatusSchema,
  CaseStatusSchema,
  ActionOriginSchema,
  CreateActionInputSchema,
  UpdateActionInputSchema,
  UpdateCaseStatusInputSchema,
  UpdateExtractedInfoInputSchema,
  UpdateMainDeadlineInputSchema,
  UpdateCaseScalarsInputSchema,
  UpdateRequiredDocInputSchema,
  RESULT_WARNING_BANNER,
  LOCKABLE_FIELDS,
  ANALYSIS_MESSAGES,
  CASE_FILE_PATHS,
} from "@capclair/contract";

export type {
  ConfirmAiConsentInput,
  CaseFileStatusResponse,
  CaseFileResultResponse,
  CaseFileHistoryResponse,
  StartAnalysisResponse,
  CaseStatus,
  ActionOrigin,
  CreateActionInput,
  UpdateActionInput,
  UpdateCaseStatusInput,
  UpdateExtractedInfoInput,
  UpdateMainDeadlineInput,
  UpdateCaseScalarsInput,
  UpdateRequiredDocInput,
  LockableField,
} from "@capclair/contract";
